name: $(Rev:rr)

pr: none
trigger: none

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-Token

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEngSS-MicroBuild2022-1ES'
    agentPoolDemandTeam: ''
    solution: '**\ServiceMonitor.sln'
    productMajor: 1
    productMinor: 0
    buildMinor: $(Build.BuildNumber)
    signType: 'real'
    indexSourcesAndPublishSymbols: 'true'
    publishArtifactInstallers: 'false'
    whiteListPathForAuthenticodeSign: '$(Build.SourcesDirectory)\IIS-Common\.azure\templates\no_authenticode.txt'
