name: $(Rev:.rr)

pr:
  - master

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-PAT

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEng-MicroBuildVS2017'
    agentPoolDemandTeam: ''
    solution: '**\ServiceMonitor.sln'
    productMajor: 2
    productMinor: 0
    buildMinor: $(Build.BuildNumber)
    signType: 'test'
    indexSourcesAndPublishSymbols: 'true'
    publishArtifactInstallers: 'false'
    whiteListPathForAuthenticodeSign: '$(Build.SourcesDirectory)\IIS-Common\.azure\templates\no_authenticode.txt'

